import '../../css/Hero.css';
import '../../css/Common.css';
import styles from './gpu-vegetation.module.css';

import UpdateFeed from '../../components/UpdateFeed';

import Background from '../../media/gpu-vegetation.gif';

const media = require.context('./media', true, /\.(png|jpe?g|svg|webp|gif)$/);

function GpuVegetation() {
    return (
        <div className={styles.gpuVegetation}>
            <img className="background fade-bottom" src={Background} alt="Background" style={{ height: "70vh" }} />
            <div className="half-width">
                <div className={styles.logoContainer} style={{ paddingTop: "20vh" }}>
                    <h1>GPU-Based Real-Time Procedural Distribution of Vegetation on Procedural Virtual Terrains</h1>
                    <h3 style={{ paddingBottom: "5vh", width: "80%", margin: "auto" }}>
                        A Unity tool that allows for the real-time procedural distribution
                        of vegetation on large-scale virtual terrains, with consideration of both abiotic
                        and biotic factors from a heightmap, based on the paper:
                        <span style={{ display: "block", marginTop: "1vh", marginBottom: "1vh", fontStyle: "italic" }}>
                            <a className="hlink" href="https://www.sbgames.org/sbgames2018/files/papers/ComputacaoFull/188348.pdf" target="_blank" rel="noreferrer">
                                "GPU-Based Real-Time Procedural Distribution of Vegetation <br /> on Procedural Virtual Terrains", Nascimento, B.T. et al. (2018).
                            </a>
                        </span>
                    </h3>
                </div>

                <div style={{ marginTop: "5vh", marginBottom: "2vh" }}>
                    <h1 className="section-header">How It Works</h1>
                    <div style={{ marginBottom: "2vh" }}>
                        <h2>1. Generating Texture Maps </h2>
                        <p>
                            The texture maps required for the vegetation distribution are generated from the heightmap.
                            These texture maps include the normal map, slope map, mean heightmap, relative heightmap,
                            water spread map, relative moisture map, and moisture map.
                        </p>
                    </div>

                    <div className={styles.guide}>
                        <div>
                            <h3>1.1. Normal and Slope Maps</h3>
                            <p>The normal map is the normalized gradient of the heightmap, and the slope map is the magnitude of the normal map.</p>
                            <div className={styles.textures}>
                                <div>
                                    <img src={media(`./height.png`)} alt="Height Map" />
                                    <p>Height Map</p>
                                </div>
                                <h1>&#8680;</h1>
                                <div>
                                    <img src={media(`./normal.png`)} alt="Normal Map" />
                                    <p>Normal Map</p>
                                </div>
                                <h1>&#8680;</h1>
                                <div>
                                    <img src={media(`./slope.png`)} alt="Slope Map" />
                                    <p>Slope Map</p>
                                </div>
                            </div>
                        </div>

                        <div>
                            <h3>1.2. Mean Height and Water Spread Maps</h3>
                            <p>The mean heightmap and water spread map is generated by applying a gaussian blur to the heightmap and
                                water map respectively. The water map is then binarily added to the water spread map.</p>
                            <div className={styles.textures}>
                                <div>
                                    <img src={media(`./height.png`)} alt="Height Map" />
                                    <p>Height Map</p>
                                </div>
                                <div>
                                    <img src={media(`./water.png`)} alt="Slope Map" />
                                    <p>Water Map</p>
                                </div>
                                <h1>⇨</h1>
                                <div>
                                    <img src={media(`./relative.png`)} alt="Mean Height Map" />
                                    <p>Mean Height Map</p>
                                </div>
                                <div>
                                    <img src={media(`./spread.png`)} alt="Slope Map" />
                                    <p>Water Spread Map</p>
                                </div>
                            </div>
                        </div>

                        <div>
                            <h3>1.3. Relative Height Map</h3>
                            <p>The relative heightmap is generated by subtracting the mean heightmap from the heightmap.</p>
                            <div className={styles.textures}>
                                <div>
                                    <img src={media(`./relative.png`)} alt="Height Map" />
                                    <p>Mean Height Map</p>
                                </div>
                                <h1>-</h1>
                                <div>
                                    <img src={media(`./height.png`)} alt="Normal Map" />
                                    <p>Height Map</p>
                                </div>
                                <h1>=</h1>
                                <div>
                                    <img src={media(`./relative.png`)} alt="Slope Map" />
                                    <p>Relative Height Map</p>
                                </div>
                            </div>
                        </div>

                        <div>
                            <h3>1.4. Relative Moisture Map</h3>
                            <p>The relative moisture map is generated by combining the relative heightmap with the slope map.</p>
                            <div className={styles.textures}>
                                <div>
                                    <img src={media(`./relative.png`)} alt="Height Map" />
                                    <p>Relative Height Map</p>
                                </div>
                                <h1>*</h1>
                                <div>
                                    <img src={media(`./slope.png`)} alt="Normal Map" />
                                    <p>Slope Map</p>
                                </div>
                                <h1>&#8680;</h1>
                                <div>
                                    <img src={media(`./r-moisture.png`)} alt="Slope Map" />
                                    <p>Relative Moisture Map</p>
                                </div>
                            </div>
                        </div>

                        <div>
                            <h3>1.5. Moisture Map</h3>
                            <p>The moisture map is generated by combining the relative height, relative moisture and water spread.</p>
                            <div className={styles.textures}>
                                <div>
                                    <img src={media(`./relative.png`)} alt="Height Map" />
                                    <p>Relative Height Map</p>
                                </div>
                                <div>
                                    <img src={media(`./r-moisture.png`)} alt="Normal Map" />
                                    <p>Relative Moisture Map</p>
                                </div>
                                <div>
                                    <img src={media(`./spread.png`)} alt="Slope Map" />
                                    <p>Water Spread Map</p>
                                </div>
                                <h1>&#8680;</h1>
                                <div>
                                    <img src={media(`./moisture.png`)} alt="Slope Map" />
                                    <p>Moisture Map</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h2>2. Sampling Texture Maps </h2>
                    <h2>3. Generating Vegetation Instances </h2>
                    <h2>4. Rendering Vegetation Instances </h2>
                </div>

                <UpdateFeed filter="gpu-vegetation" />

                <div style={{ marginTop: "5vh", paddingBottom: "5vh" }}>
                    <h1 className="section-header">Motivation Behind Project</h1>
                    <p>

                    </p>
                </div>
            </div>
        </div>
    );
}

export default GpuVegetation;
